displayName=Bolt Proc Counter
author=ttortt / hyppis
description=Bolt Proc Counter (Sound effects must be enabled for tracking procs)
tags=hint,gear,counter,tracker
plugins=com.BoltProcCounter.BoltProcCounterPlugin
build=standard